# Generated by Django 5.0.6 on 2024-07-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcap_upload', '0003_remove_pcapfile_file_remove_pcapfile_json_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packetdata',
            name='pcap_file',
        ),
    ]
